
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"  crossorigin="anonymous">
    <link href="fontawesome-free/css/all.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="style.css">
    <script src="https://kit.fontawesome.com/51b16e748f.js" crossorigin="anonymous"></script>

    <title>Treatment Finder</title>
    <script>

        

    </script>
    <%
        String search = request.getParameter("desc");
        String location = request.getParameter("location");
        String d = request.getParameter("distance");
        
        int distance = 0;
        String error = request.getParameter("error");
        if(search == null) search="";
        if(location == null) location="";
        if(d == null);
        else distance = Integer.parseInt(d);
        
        if(error == null) error="0";
        else error = "1";
    %>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script> 
    <link rel="stylesheet" href="style.css">
    <script src="https://kit.fontawesome.com/51b16e748f.js" crossorigin="anonymous"></script>
    <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/favicon-16x16.png">
    <link rel="manifest" href="img/site.webmanifest">
    <script src="./jquery.suggest.js"></script>
    
    <title>Treatment Finder</title>
    <script>
        function updateTextInput(val) {
          document.getElementById('textInput').value=val;
        }
    </script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

        <div class="container">
          <a class="navhead navbar-brand" href="index.html"><h4>Treatment <span class="accent">Finder</span></h4></a>
        </div>
    </nav>

    <main role="main">
      <div id="header" class="container">
        <br>
        <h1>Let's find you some affordable</h1>
        <h1>health care!</h1>

      <form action="search.jsp" method="post" id="form">

        <br>


        <!--Start of row 1-->
        <div class="form-group">
        <div class="row">
          <div class="col">

              <div class="input-group">
                <div class="input-group-prepend">
                    <select id="searchBy" name="searchBy" class="btn btn-outline-secondary dropdown-toggle">
                        <option value="code" selected="selected">DRG Code</option>
                        <option value="desc">Description</option>
                    </select>
                  
                </div>
                <input name="desc" id="desc" autocomplete="off" type="text" class="form-control form-control-lg" placeholder="eg - 023" required/>
              </div>

          </div>
        </div>
        </br>
          <!--Start of row 2-->
          <div class="row">
            <div class="col">
                <input id="browser-location-lat" name="browser-location-lat" type="hidden">
                <input id="browser-location-lon" name="browser-location-lon" type="hidden">
                <div class="input-group">

                    <input id="location-input" name="location" type="text" class="form-control form-control-lg" value="<% out.print(location); %>" placeholder="Where are you from?" aria-label="Recipient's username" aria-describedby="basic-addon2" required>

                <div class="input-group-append">
                    <button id="own-location" class="btn btn-primary" type="button"><i class="fas fa-map-pin"></i></button>
                  </div>
                </div>
            </div>
            <div class="col">

        <div class="input-group">
                <div class="input-group-append">
          
        </div>
              <input  placeholder="How many miles are you willing to travel?" type="number" class="form-control form-control-lg" step="5" name="max-distance" min="0" >
              <div class="input-group-text">miles</div>
        </div>
        </div>

          </div>
            </br>
          <!--Start of row 3-->
          <div class="slidecontainer col-13">
		  <div class="row">
                <div class="col">
                      <label>Minimum Price </label>
                </div>
                <div class="col">
                      <label class="col-12 text-right" >Maximum price</label>
                </div>
              </div> 
                    <label>Maximum Price</label>
                    <input type="range" class="custom-range" id="range" min="0" max="600000" step="500" oninput="change()" onchange="change()" >
                    <label>$<input type="text" name="price" id="price" value="300000" style="border:none;"></label>
                    <script type='text/javascript'>
			function change() {
  				var value = document.getElementById('range').value ;
  				document.getElementById('price').value = value;
			}
                    </script>
          </div>
        </div>
          <div id="error">
              
          </div>
          <% 
            if(error == "1") out.print("<t1><font color=\"red\">No result. Please change options for more results</font></t1>");
            else out.print("</br>");
          %>
          <button type="submit" class="btn btn-primary btn-block search-button">Search</button>

        </div>
      </form>
    </main>


    <footer class="footer bg-light">
            <div class="container">
                <div class="row">
              <p class="p-0 m-0">© Team 15 2020</p>
              <div class="float-right">
                <i class="fab fa-twitter-square fa-2x fa-fw align-middle"></i><i class="fab fa-facebook fa-2x fa-fw align-middle"></i><i class="fab fa-instagram fa-2x fa-fw align-middle"></i>
              </div>
                </div>
            </div>
        </footer>
      <script>
    var bLocationLat = document.getElementById("browser-location-lat");
    var bLocationLon = document.getElementById("browser-location-lon");
    function getLocation() {
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
      } else {
        document.getELementById("location-input").value = "New York";
      }
    }
    
    $("#own-location").on("click", function(){
       if($("#location-input").prop("disabled")) {
           $("#location-input").prop("disabled", false);
           $("#location-input").prop("required", true);
           $("#location-input").attr("placeholder", "Where are you from?");
           return;
       }
       $("#location-input").attr("placeholder", "Using your location");
       $("#location-input").prop("required", false);
       $("#location-input").prop("disabled", true);
       
    });

    function showPosition(position) {
      bLocationLat.value = position.coords.latitude;
      bLocationLon.value = position.coords.longitude;
    }
    
    getLocation();
    
    $("#form").on("submit", function(e){
        var select = $("#searchBy").val();
        
        if(select === "desc") {
            if($.inArray($("#desc").val(), listOfProcedures) === -1) {
                e.preventDefault();
                $("#error").html("<t1><font color=\"red\">This is not a valid procedure, please try again using a suggested procedure.</font></t1>");
            }
        }
        else {
            if($.inArray($("#desc").val().replace(/^0+/, ''), listOfCodes) === -1) {
                e.preventDefault();
                $("#error").html("<t1><font color=\"red\">This is not a valid procedure, please try again using a suggested procedure.</font></t1>");
            }
        }
    })
    
    var listOfCodes = [
        "23",
        "25",
        "27",
        "37",
        "38",
        "39",
        "54",
        "56",
        "57",
        "62",
        "64",
        "65",
        "66",
        "69",
        "70",
        "71",
        "73",
        "74",
        "86",
        "87",
        "91",
        "92",
        "100",
        "101",
        "103",
        "149",
        "163",
        "164",
        "166",
        "176",
        "177",
        "180",
        "189",
        "190",
        "191",
        "192",
        "193",
        "194",
        "195",
        "202",
        "203",
        "207",
        "208",
        "216",
        "229",
        "233",
        "234",
        "236",
        "242",
        "243",
        "244",
        "246",
        "247",
        "252",
        "264",
        "269",
        "270",
        "271",
        "280",
        "281",
        "282",
        "283",
        "286",
        "287",
        "291",
        "292",
        "293",
        "299",
        "300",
        "303",
        "304",
        "305",
        "308",
        "309",
        "310",
        "312",
        "313",
        "314",
        "315",
        "329",
        "330",
        "331",
        "356",
        "371",
        "372",
        "377",
        "378",
        "388",
        "389",
        "390",
        "391",
        "392",
        "393",
        "394",
        "417",
        "418",
        "419",
        "432",
        "435",
        "439",
        "440",
        "441",
        "442",
        "460",
        "467",
        "469",
        "470",
        "472",
        "473",
        "480",
        "481",
        "483",
        "493",
        "516",
        "536",
        "543",
        "551",
        "552",
        "563",
        "603",
        "637",
        "638",
        "639",
        "640",
        "641",
        "658",
        "673",
        "682",
        "683",
        "689",
        "690",
        "698",
        "699",
        "708",
        "781",
        "811",
        "812",
        "813",
        "840",
        "853",
        "854",
        "862",
        "870",
        "871",
        "872",
        "881",
        "884",
        "885",
        "896",
        "897",
        "917",
        "918",
        "919",
        "920",
        "981",
        "982",
        "178",
        "253",
        "254",
        "379",
        "482",
        "621",
        "684",
        "948",
        "175",
        "199",
        "206",
        "251",
        "268",
        "301",
        "445",
        "669",
        "4",
        "220",
        "266",
        "327",
        "602",
        "249",
        "694",
        "153",
        "895",
        "3",
        "186",
        "187",
        "204",
        "239",
        "240",
        "438",
        "455",
        "494",
        "517",
        "617",
        "462",
        "1",
        "5",
        "6",
        "11",
        "12",
        "13",
        "16",
        "20",
        "24",
        "26",
        "29",
        "40",
        "55",
        "82",
        "83",
        "85",
        "93",
        "129",
        "130",
        "131",
        "133",
        "134",
        "165",
        "167",
        "168",
        "196",
        "197",
        "200",
        "205",
        "219",
        "228",
        "235",
        "267",
        "273",
        "274",
        "306",
        "326",
        "328",
        "354",
        "355",
        "357",
        "374",
        "375",
        "386",
        "405",
        "406",
        "407",
        "433",
        "444",
        "456",
        "457",
        "459",
        "463",
        "464",
        "466",
        "475",
        "478",
        "492",
        "501",
        "515",
        "518",
        "519",
        "554",
        "580",
        "607",
        "623",
        "643",
        "644",
        "652",
        "656",
        "657",
        "659",
        "660",
        "674",
        "737",
        "740",
        "742",
        "743",
        "748",
        "765",
        "775",
        "808",
        "809",
        "822",
        "827",
        "834",
        "837",
        "838",
        "841",
        "846",
        "847",
        "856",
        "857",
        "863",
        "866",
        "880",
        "907",
        "908",
        "928",
        "935",
        "947",
        "956",
        "957",
        "958",
        "963",
        "964",
        "974",
        "975",
        "983",
        "987",
        "33",
        "68",
        "184",
        "221",
        "227",
        "250",
        "302",
        "337",
        "373",
        "395",
        "436",
        "454",
        "465",
        "468",
        "471",
        "520",
        "546",
        "556",
        "558",
        "579",
        "605",
        "645",
        "864",
        "988",
        "883",
        "311",
        "181",
        "41",
        "248",
        "707",
        "336",
        "713",
        "179",
        "261",
        "316",
        "562",
        "581",
        "628",
        "35",
        "36",
        "215",
        "272",
        "592",
        "620",
        "696",
        "916",
        "61",
        "84",
        "542",
        "544",
        "560",
        "335",
        "345",
        "728",
        "7",
        "28",
        "31",
        "32",
        "614",
        "535",
        "17",
        "446",
        "627",
        "571",
        "629",
        "573",
        "902",
        "904",
        "14",
        "545",
        "654",
        "821",
        "226",
        "489",
        "217",
        "225",
        "458",
        "384",
        "498",
        "642",
        "823",
        "824",
        "909",
        "714",
        "882",
        "741",
        "949",
        "453",
        "380",
        "381",
        "923",
        "940",
        "369",
        "152",
        "570",
        "894",
        "72",
        "557",
        "183",
        "734",
        "89",
        "479",
        "565",
        "502",
        "185",
        "626",
        "653",
        "843",
        "577",
        "661",
        "700",
        "343",
        "352",
        "307",
        "351",
        "474",
        "477",
        "486",
        "488",
        "553",
        "564",
        "615",
        "668",
        "717",
        "865",
        "977",
        "718",
        "63",
        "835",
        "59",
        "868",
        "887",
        "125",
        "154",
        "155",
        "260",
        "339",
        "353",
        "368",
        "500",
        "511",
        "596",
        "755",
        "867",
        "869",
        "60",
        "151",
        "156",
        "158",
        "415",
        "540",
        "616",
        "8",
        "30",
        "574",
        "224",
        "245",
        "296",
        "78",
        "123",
        "385",
        "387",
        "504",
        "510",
        "512",
        "514",
        "539",
        "555",
        "559",
        "597",
        "598",
        "604",
        "606",
        "666",
        "670",
        "727",
        "736",
        "754",
        "760",
        "815",
        "816",
        "820",
        "914",
        "139",
        "655",
        "876",
        "921",
        "593",
        "42",
        "561",
        "839",
        "115",
        "340",
        "929",
        "829",
        "849",
        "746",
        "90",
        "58",
        "747",
        "443",
        "693",
        "416",
        "945",
        "437",
        "585",
        "687",
        "950",
        "946",
        "726",
        "52",
        "53",
        "423",
        "578",
        "624",
        "844",
        "114",
        "117",
        "147",
        "408",
        "774",
        "583",
        "137",
        "595",
        "513",
        "157",
        "348",
        "496",
        "497",
        "814",
        "828",
        "842",
        "941",
        "231",
        "262",
        "735",
        "901",
        "259",
        "989",
        "97",
        "222",
        "420",
        "625",
        "951",
        "132",
        "934",
        "619",
        "622",
        "98",
        "744",
        "102",
        "547",
        "255",
        "414",
        "77",
        "256",
        "686",
        "766",
        "201",
        "198"
    ];
    
    var listOfProcedures = [
         "Craniotomy w major device implant or acute cns pdx w mcc or chemothe",
            "Craniotomy & endovascular intracranial procedures w mcc",
            "Craniotomy & endovascular intracranial procedures w/o cc/mcc",
            "Extracranial procedures w mcc",
            "Extracranial procedures w cc",
            "Extracranial procedures w/o cc/mcc",
            "Nervous system neoplasms w mcc",
            "Degenerative nervous system disorders w mcc",
            "Degenerative nervous system disorders w/o mcc",
            "Ischemic stroke, precerebral occlusion or transient ischemia w throm",
            "Intracranial hemorrhage or cerebral infarction w mcc",
            "Intracranial hemorrhage or cerebral infarction w cc or tpa in 24 hrs",
            "Intracranial hemorrhage or cerebral infarction w/o cc/mcc",
            "Transient ischemia",
            "Nonspecific cerebrovascular disorders w mcc",
            "Nonspecific cerebrovascular disorders w cc",
            "Cranial & peripheral nerve disorders w mcc",
            "Cranial & peripheral nerve disorders w/o mcc",
            "Traumatic stupor & coma, coma <1 hr w cc",
            "Traumatic stupor & coma, coma <1 hr w/o cc/mcc",
            "Other disorders of nervous system w mcc",
            "Other disorders of nervous system w cc",
            "Seizures w mcc",
            "Seizures w/o mcc",
            "Headaches w/o mcc",
            "Dysequilibrium",
            "Major chest procedures w mcc",
            "Major chest procedures w cc",
            "Other resp system o.r. procedures w mcc",
            "Pulmonary embolism w/o mcc",
            "Respiratory infections & inflammations w mcc",
            "Respiratory neoplasms w mcc",
            "Pulmonary edema & respiratory failure",
            "Chronic obstructive pulmonary disease w mcc",
            "Chronic obstructive pulmonary disease w cc",
            "Chronic obstructive pulmonary disease w/o cc/mcc",
            "Simple pneumonia & pleurisy w mcc",
            "Simple pneumonia & pleurisy w cc",
            "Simple pneumonia & pleurisy w/o cc/mcc",
            "Bronchitis & asthma w cc/mcc",
            "Bronchitis & asthma w/o cc/mcc",
            "Respiratory system diagnosis w ventilator support >96 hours",
            "Respiratory system diagnosis w ventilator support <=96 hours",
            "Cardiac valve & oth maj cardiothoracic proc w card cath w mcc",
            "Other cardiothoracic procedures w/o mcc",
            "Coronary bypass w cardiac cath w mcc",
            "Coronary bypass w cardiac cath w/o mcc",
            "Coronary bypass w/o cardiac cath w/o mcc",
            "Permanent cardiac pacemaker implant w mcc",
            "Permanent cardiac pacemaker implant w cc",
            "Permanent cardiac pacemaker implant w/o cc/mcc",
            "Perc cardiovasc proc w drug-eluting stent w mcc or 4+ vessels/stents",
            "Perc cardiovasc proc w drug-eluting stent w/o mcc",
            "Other vascular procedures w mcc",
            "Other circulatory system o.r. procedures",
            "Aortic and heart assist procedures except pulsation balloon w/o mcc",
            "Other major cardiovascular procedures w mcc",
            "Other major cardiovascular procedures w cc",
            "Acute myocardial infarction, discharged alive w mcc",
            "Acute myocardial infarction, discharged alive w cc",
            "Acute myocardial infarction, discharged alive w/o cc/mcc",
            "Acute myocardial infarction, expired w mcc",
            "Circulatory disorders except ami, w card cath w mcc",
            "Circulatory disorders except ami, w card cath w/o mcc",
            "Heart failure & shock w mcc",
            "Heart failure & shock w cc",
            "Heart failure & shock w/o cc/mcc",
            "Peripheral vascular disorders w mcc",
            "Peripheral vascular disorders w cc",
            "Atherosclerosis w/o mcc",
            "Hypertension w mcc",
            "Hypertension w/o mcc",
            "Cardiac arrhythmia & conduction disorders w mcc",
            "Cardiac arrhythmia & conduction disorders w cc",
            "Cardiac arrhythmia & conduction disorders w/o cc/mcc",
            "Syncope & collapse",
            "Chest pain",
            "Other circulatory system diagnoses w mcc",
            "Other circulatory system diagnoses w cc",
            "Major small & large bowel procedures w mcc",
            "Major small & large bowel procedures w cc",
            "Major small & large bowel procedures w/o cc/mcc",
            "Other digestive system o.r. procedures w mcc",
            "Major gastrointestinal disorders & peritoneal infections w mcc",
            "Major gastrointestinal disorders & peritoneal infections w cc",
            "G.i. hemorrhage w mcc",
            "G.i. hemorrhage w cc",
            "G.i. obstruction w mcc",
            "G.i. obstruction w cc",
            "G.i. obstruction w/o cc/mcc",
            "Esophagitis, gastroent & misc digest disorders w mcc",
            "Esophagitis, gastroent & misc digest disorders w/o mcc",
            "Other digestive system diagnoses w mcc",
            "Other digestive system diagnoses w cc",
            "Laparoscopic cholecystectomy w/o c.d.e. w mcc",
            "Laparoscopic cholecystectomy w/o c.d.e. w cc",
            "Laparoscopic cholecystectomy w/o c.d.e. w/o cc/mcc",
            "Cirrhosis & alcoholic hepatitis w mcc",
            "Malignancy of hepatobiliary system or pancreas w mcc",
            "Disorders of pancreas except malignancy w cc",
            "Disorders of pancreas except malignancy w/o cc/mcc",
            "Disorders of liver except malig,cirr,alc hepa w mcc",
            "Disorders of liver except malig,cirr,alc hepa w cc",
            "Spinal fusion except cervical w/o mcc",
            "Revision of hip or knee replacement w cc",
            "Major hip and knee joint replacement or reattachment of lower extrem",
            "Major joint replacement or reattachment of lower extremity w/o mcc",
            "Cervical spinal fusion w cc",
            "Cervical spinal fusion w/o cc/mcc",
            "Hip & femur procedures except major joint w mcc",
            "Hip & femur procedures except major joint w cc",
            "Major joint/limb reattachment procedure of upper extremities",
            "Lower extrem & humer proc except hip,foot,femur w cc",
            "Other musculoskelet sys & conn tiss o.r. proc w cc",
            "Fractures of hip & pelvis w/o mcc",
            "Pathological fractures & musculoskelet & conn tiss malig w cc",
            "Medical back problems w mcc",
            "Medical back problems w/o mcc",
            "Fx, sprn, strn & disl except femur, hip, pelvis & thigh w/o mcc",
            "Cellulitis w/o mcc",
            "Diabetes w mcc",
            "Diabetes w cc",
            "Diabetes w/o cc/mcc",
            "Misc disorders of nutrition,metabolism,fluids/electrolytes w mcc",
            "Misc disorders of nutrition,metabolism,fluids/electrolytes w/o mcc",
            "Kidney & ureter procedures for neoplasm w/o cc/mcc",
            "Other kidney & urinary tract procedures w mcc",
            "Renal failure w mcc",
            "Renal failure w cc",
            "Kidney & urinary tract infections w mcc",
            "Kidney & urinary tract infections w/o mcc",
            "Other kidney & urinary tract diagnoses w mcc",
            "Other kidney & urinary tract diagnoses w cc",
            "Major male pelvic procedures w/o cc/mcc",
            "Other antepartum diagnoses w medical complications",
            "Red blood cell disorders w mcc",
            "Red blood cell disorders w/o mcc",
            "Coagulation disorders",
            "Lymphoma & non-acute leukemia w mcc",
            "Infectious & parasitic diseases w o.r. procedure w mcc",
            "Infectious & parasitic diseases w o.r. procedure w cc",
            "Postoperative & post-traumatic infections w mcc",
            "Septicemia or severe sepsis w mv >96 hours",
            "Septicemia or severe sepsis w/o mv >96 hours w mcc",
            "Septicemia or severe sepsis w/o mv >96 hours w/o mcc",
            "Depressive neuroses",
            "Organic disturbances & intellectual disability",
            "Psychoses",
            "Alcohol/drug abuse or dependence w/o rehabilitation therapy w mcc",
            "Alcohol/drug abuse or dependence w/o rehabilitation therapy w/o mcc",
            "Poisoning & toxic effects of drugs w mcc",
            "Poisoning & toxic effects of drugs w/o mcc",
            "Complications of treatment w mcc",
            "Complications of treatment w cc",
            "Extensive o.r. procedure unrelated to principal diagnosis w mcc",
            "Extensive o.r. procedure unrelated to principal diagnosis w cc",
            "Respiratory infections & inflammations w cc",
            "Other vascular procedures w cc",
            "Other vascular procedures w/o cc/mcc",
            "G.i. hemorrhage w/o cc/mcc",
            "Hip & femur procedures except major joint w/o cc/mcc",
            "O.r. procedures for obesity w/o cc/mcc",
            "Renal failure w/o cc/mcc",
            "Signs & symptoms w/o mcc",
            "Pulmonary embolism w mcc",
            "Pneumothorax w mcc",
            "Other respiratory system diagnoses w/o mcc",
            "Perc cardiovasc proc w/o coronary artery stent w/o mcc",
            "Aortic and heart assist procedures except pulsation balloon w mcc",
            "Peripheral vascular disorders w/o cc/mcc",
            "Disorders of the biliary tract w cc",
            "Transurethral procedures w cc",
            "Trach w mv >96 hrs or pdx exc face, mouth & neck w/o maj o.r.",
            "Cardiac valve & oth maj cardiothoracic proc w/o card cath w cc",
            "Endovascular cardiac valve replacement w mcc",
            "Stomach, esophageal & duodenal proc w cc",
            "Cellulitis w mcc",
            "Perc cardiovasc proc w non-drug-eluting stent w/o mcc",
            "Urinary stones w/o esw lithotripsy w/o mcc",
            "Otitis media & uri w/o mcc",
            "Alcohol/drug abuse or dependence w rehabilitation therapy",
            "Ecmo or trach w mv >96 hrs or pdx exc face, mouth & neck w maj o.r.",
            "Pleural effusion w mcc",
            "Pleural effusion w cc",
            "Respiratory signs & symptoms",
            "Amputation for circ sys disorders exc upper limb & toe w mcc",
            "Amputation for circ sys disorders exc upper limb & toe w cc",
            "Disorders of pancreas except malignancy w mcc",
            "Combined anterior/posterior spinal fusion w/o cc/mcc",
            "Lower extrem & humer proc except hip,foot,femur w/o cc/mcc",
            "Other musculoskelet sys & conn tiss o.r. proc w/o cc/mcc",
            "Amputat of lower limb for endocrine,nutrit,& metabol dis w cc",
            "Bilateral or multiple major joint procs of lower extremity w/o mcc",
            "Heart transplant or implant of heart assist system w mcc",
            "Liver transplant w mcc or intestinal transplant",
            "Liver transplant w/o mcc",
            "Tracheostomy for face,mouth & neck diagnoses w mcc",
            "Tracheostomy for face,mouth & neck diagnoses w cc",
            "Tracheostomy for face,mouth & neck diagnoses w/o cc/mcc",
            "Autologous bone marrow transplant w cc/mcc",
            "Intracranial vascular procedures w pdx hemorrhage w mcc",
            "Cranio w major dev impl/acute complex cns pdx w/o mcc",
            "Craniotomy & endovascular intracranial procedures w cc",
            "Spinal procedures w cc or spinal neurostimulators",
            "Periph/cranial nerve & other nerv syst proc w mcc",
            "Nervous system neoplasms w/o mcc",
            "Traumatic stupor & coma, coma >1 hr w mcc",
            "Traumatic stupor & coma, coma >1 hr w cc",
            "Traumatic stupor & coma, coma <1 hr w mcc",
            "Other disorders of nervous system w/o cc/mcc",
            "Major head & neck procedures w cc/mcc or major device",
            "Major head & neck procedures w/o cc/mcc",
            "Cranial/facial procedures w cc/mcc",
            "Other ear, nose, mouth & throat o.r. procedures w cc/mcc",
            "Other ear, nose, mouth & throat o.r. procedures w/o cc/mcc",
            "Major chest procedures w/o cc/mcc",
            "Other resp system o.r. procedures w cc",
            "Other resp system o.r. procedures w/o cc/mcc",
            "Interstitial lung disease w mcc",
            "Interstitial lung disease w cc",
            "Pneumothorax w cc",
            "Other respiratory system diagnoses w mcc",
            "Cardiac valve & oth maj cardiothoracic proc w/o card cath w mcc",
            "Other cardiothoracic procedures w mcc",
            "Coronary bypass w/o cardiac cath w mcc",
            "Endovascular cardiac valve replacement w/o mcc",
            "Percutaneous intracardiac procedures w mcc",
            "Percutaneous intracardiac procedures w/o mcc",
            "Cardiac congenital & valvular disorders w mcc",
            "Stomach, esophageal & duodenal proc w mcc",
            "Stomach, esophageal & duodenal proc w/o cc/mcc",
            "Hernia procedures except inguinal & femoral w cc",
            "Hernia procedures except inguinal & femoral w/o cc/mcc",
            "Other digestive system o.r. procedures w cc",
            "Digestive malignancy w mcc",
            "Digestive malignancy w cc",
            "Inflammatory bowel disease w cc",
            "Pancreas, liver & shunt procedures w mcc",
            "Pancreas, liver & shunt procedures w cc",
            "Pancreas, liver & shunt procedures w/o cc/mcc",
            "Cirrhosis & alcoholic hepatitis w cc",
            "Disorders of the biliary tract w mcc",
            "Spinal fus exc cerv w spinal curv/malig/infec or ext fus w mcc",
            "Spinal fus exc cerv w spinal curv/malig/infec or ext fus w cc",
            "Spinal fusion except cervical w mcc",
            "Wnd debrid & skn grft exc hand, for musculo-conn tiss dis w mcc",
            "Wnd debrid & skn grft exc hand, for musculo-conn tiss dis w cc",
            "Revision of hip or knee replacement w mcc",
            "Amputation for musculoskeletal sys & conn tissue dis w cc",
            "Biopsies of musculoskeletal system & connective tissue w cc",
            "Lower extrem & humer proc except hip,foot,femur w mcc",
            "Soft tissue procedures w cc",
            "Other musculoskelet sys & conn tiss o.r. proc w mcc",
            "Back & neck proc exc spinal fusion w mcc or disc device/neurostim",
            "Back & neck proc exc spinal fusion w cc",
            "Bone diseases & arthropathies w/o mcc",
            "Other skin, subcut tiss & breast proc w cc",
            "Minor skin disorders w/o mcc",
            "Skin grafts & wound debrid for endoc, nutrit & metab dis w cc",
            "Endocrine disorders w mcc",
            "Endocrine disorders w cc",
            "Kidney transplant",
            "Kidney & ureter procedures for neoplasm w mcc",
            "Kidney & ureter procedures for neoplasm w cc",
            "Kidney & ureter procedures for non-neoplasm w mcc",
            "Kidney & ureter procedures for non-neoplasm w cc",
            "Other kidney & urinary tract procedures w cc",
            "Uterine & adnexa proc for ovarian or adnexal malignancy w cc",
            "Uterine,adnexa proc for non-ovarian/adnexal malig w cc",
            "Uterine & adnexa proc for non-malignancy w cc/mcc",
            "Uterine & adnexa proc for non-malignancy w/o cc/mcc",
            "Female reproductive system reconstructive procedures",
            "Cesarean section w cc/mcc",
            "Vaginal delivery w/o complicating diagnoses",
            "Major hematol/immun diag exc sickle cell crisis & coagul w mcc",
            "Major hematol/immun diag exc sickle cell crisis & coagul w cc",
            "Lymphoma & leukemia w major o.r. procedure w/o cc/mcc",
            "Myeloprolif disord or poorly diff neopl w maj o.r. proc w cc",
            "Acute leukemia w/o major o.r. procedure w mcc",
            "Chemo w acute leukemia as sdx or w high dose chemo agent w mcc",
            "Chemo w acute leukemia as sdx w cc or high dose chemo agent",
            "Lymphoma & non-acute leukemia w cc",
            "Chemotherapy w/o acute leukemia as secondary diagnosis w mcc",
            "Chemotherapy w/o acute leukemia as secondary diagnosis w cc",
            "Postoperative or post-traumatic infections w o.r. proc w mcc",
            "Postoperative or post-traumatic infections w o.r. proc w cc",
            "Postoperative & post-traumatic infections w/o mcc",
            "Viral illness w/o mcc",
            "Acute adjustment reaction & psychosocial dysfunction",
            "Other o.r. procedures for injuries w mcc",
            "Other o.r. procedures for injuries w cc",
            "Full thickness burn w skin graft or inhal inj w cc/mcc",
            "Non-extensive burns",
            "Signs & symptoms w mcc",
            "Limb reattachment, hip & femur proc for multiple significant trauma",
            "Other o.r. procedures for multiple significant trauma w mcc",
            "Other o.r. procedures for multiple significant trauma w cc",
            "Other multiple significant trauma w mcc",
            "Other multiple significant trauma w cc",
            "Hiv w major related condition w mcc",
            "Hiv w major related condition w cc",
            "Extensive o.r. procedure unrelated to principal diagnosis w/o cc/mcc",
            "Non-extensive o.r. proc unrelated to principal diagnosis w mcc",
            "Ventricular shunt procedures w/o cc/mcc",
            "Nonspecific cva & precerebral occlusion w/o infarct w/o mcc",
            "Major chest trauma w cc",
            "Cardiac valve & oth maj cardiothoracic proc w/o card cath w/o cc/mcc",
            "Cardiac defibrillator implant w/o cardiac cath w/o mcc",
            "Perc cardiovasc proc w/o coronary artery stent w mcc",
            "Atherosclerosis w mcc",
            "Peritoneal adhesiolysis w/o cc/mcc",
            "Major gastrointestinal disorders & peritoneal infections w/o cc/mcc",
            "Other digestive system diagnoses w/o cc/mcc",
            "Malignancy of hepatobiliary system or pancreas w cc",
            "Combined anterior/posterior spinal fusion w cc",
            "Wnd debrid & skn grft exc hand, for musculo-conn tiss dis w/o cc/mcc",
            "Revision of hip or knee replacement w/o cc/mcc",
            "Cervical spinal fusion w mcc",
            "Back & neck proc exc spinal fusion w/o cc/mcc",
            "Connective tissue disorders w cc",
            "Signs & symptoms of musculoskeletal system & conn tissue w/o mcc",
            "Tendonitis, myositis & bursitis w/o mcc",
            "Other skin, subcut tiss & breast proc w mcc",
            "Trauma to the skin, subcut tiss & breast w/o mcc",
            "Endocrine disorders w/o cc/mcc",
            "Fever",
            "Non-extensive o.r. proc unrelated to principal diagnosis w cc",
            "Disorders of personality & impulse control",
            "Angina pectoris",
            "Respiratory neoplasms w cc",
            "Periph/cranial nerve & other nerv syst proc w cc or periph neurostim",
            "Perc cardiovasc proc w non-drug-eluting stent w mcc or 4+ ves/stents",
            "Major male pelvic procedures w cc/mcc",
            "Peritoneal adhesiolysis w cc",
            "Transurethral prostatectomy w cc/mcc",
            "Respiratory infections & inflammations w/o cc/mcc",
            "Cardiac pacemaker revision except device replacement w cc",
            "Other circulatory system diagnoses w/o cc/mcc",
            "Fx, sprn, strn & disl except femur, hip, pelvis & thigh w mcc",
            "Other skin, subcut tiss & breast proc w/o cc/mcc",
            "Other endocrine, nutrit & metab o.r. proc w mcc",
            "Carotid artery stent procedure w cc",
            "Carotid artery stent procedure w/o cc/mcc",
            "Other heart assist system implant",
            "Other major cardiovascular procedures w/o cc/mcc",
            "Skin ulcers w mcc",
            "O.r. procedures for obesity w cc",
            "Kidney & urinary tract signs & symptoms w/o mcc",
            "Allergic reactions w/o mcc",
            "Acute ischemic stroke w use of thrombolytic agent w mcc",
            "Traumatic stupor & coma, coma >1 hr w/o cc/mcc",
            "Pathological fractures & musculoskelet & conn tiss malig w mcc",
            "Pathological fractures & musculoskelet & conn tiss malig w/o cc/mcc",
            "Aftercare, musculoskeletal system & connective tissue w cc",
            "Peritoneal adhesiolysis w mcc",
            "Minor small & large bowel procedures w cc",
            "Inflammation of the male reproductive system w/o mcc",
            "Lung transplant",
            "Spinal procedures w mcc",
            "Ventricular shunt procedures w mcc",
            "Ventricular shunt procedures w cc",
            "Adrenal & pituitary procedures w cc/mcc",
            "Fractures of hip & pelvis w mcc",
            "Autologous bone marrow transplant w/o cc/mcc",
            "Disorders of the biliary tract w/o cc/mcc",
            "Thyroid, parathyroid & thyroglossal procedures w/o cc/mcc",
            "Skin debridement w cc",
            "Other endocrine, nutrit & metab o.r. proc w cc",
            "Skin graft for skin ulcer or cellulitis w mcc",
            "Wound debridements for injuries w cc",
            "Skin grafts for injuries w cc/mcc",
            "Allogeneic bone marrow transplant",
            "Connective tissue disorders w mcc",
            "Major bladder procedures w cc",
            "Lymphoma & leukemia w major o.r. procedure w cc",
            "Cardiac defibrillator implant w/o cardiac cath w mcc",
            "Knee procedures w/o pdx of infection w/o cc/mcc",
            "Cardiac valve & oth maj cardiothoracic proc w card cath w cc",
            "Cardiac defib implant w cardiac cath w/o ami/hf/shock w/o mcc",
            "Spinal fus exc cerv w spinal curv/malig/infec or ext fus w/o cc/mcc",
            "Uncomplicated peptic ulcer w/o mcc",
            "Local excision & removal int fix devices of hip & femur w cc/mcc",
            "Inborn and other disorders of metabolism",
            "Lymphoma & non-acute leukemia w other proc w mcc",
            "Lymphoma & non-acute leukemia w other o.r. proc w cc",
            "Other o.r. procedures for injuries w/o cc/mcc",
            "Transurethral prostatectomy w/o cc/mcc",
            "Neuroses except depressive",
            "Uterine,adnexa proc for non-ovarian/adnexal malig w/o cc/mcc",
            "Aftercare w cc/mcc",
            "Combined anterior/posterior spinal fusion w mcc",
            "Complicated peptic ulcer w mcc",
            "Complicated peptic ulcer w cc",
            "Other injury, poisoning & toxic effect diag w/o mcc",
            "O.r. proc w diagnoses of other contact w health services w cc",
            "Major esophageal disorders w cc",
            "Otitis media & uri w mcc",
            "Skin debridement w mcc",
            "Alcohol/drug abuse or dependence, left ama",
            "Nonspecific cerebrovascular disorders w/o cc/mcc",
            "Tendonitis, myositis & bursitis w mcc",
            "Major chest trauma w mcc",
            "Pelvic evisceration, rad hysterectomy & rad vulvectomy w cc/mcc",
            "Concussion w cc",
            "Biopsies of musculoskeletal system & connective tissue w/o cc/mcc",
            "Other musculoskeletal sys & connective tissue diagnoses w cc",
            "Soft tissue procedures w/o cc/mcc",
            "Major chest trauma w/o cc/mcc",
            "Thyroid, parathyroid & thyroglossal procedures w cc",
            "Major bladder procedures w mcc",
            "Other myeloprolif dis or poorly diff neopl diag w mcc",
            "Skin graft exc for skin ulcer or cellulitis w cc",
            "Kidney & ureter procedures for non-neoplasm w/o cc/mcc",
            "Other kidney & urinary tract diagnoses w/o cc/mcc",
            "Appendectomy w/o complicated principal diag w/o cc/mcc",
            "Inguinal & femoral hernia procedures w/o cc/mcc",
            "Cardiac congenital & valvular disorders w/o mcc",
            "Inguinal & femoral hernia procedures w cc",
            "Amputation for musculoskeletal sys & conn tissue dis w mcc",
            "Biopsies of musculoskeletal system & connective tissue w mcc",
            "Knee procedures w pdx of infection w cc",
            "Knee procedures w/o pdx of infection w cc/mcc",
            "Bone diseases & arthropathies w mcc",
            "Other musculoskeletal sys & connective tissue diagnoses w mcc",
            "Adrenal & pituitary procedures w/o cc/mcc",
            "Transurethral procedures w mcc",
            "Other male reproductive system o.r. proc exc malignancy w cc/mcc",
            "Viral illness w mcc",
            "Hiv w or w/o other related condition",
            "Other male reproductive system o.r. proc exc malignancy w/o cc/mcc",
            "Acute ischemic stroke w use of thrombolytic agent w/o cc/mcc",
            "Acute leukemia w/o major o.r. procedure w cc",
            "Multiple sclerosis & cerebellar ataxia w cc",
            "Other infectious & parasitic diseases diagnoses w cc",
            "Other mental disorder diagnoses",
            "Other disorders of the eye w/o mcc",
            "Other ear, nose, mouth & throat diagnoses w mcc",
            "Other ear, nose, mouth & throat diagnoses w cc",
            "Cardiac pacemaker revision except device replacement w mcc",
            "Appendectomy w complicated principal diag w cc",
            "Hernia procedures except inguinal & femoral w mcc",
            "Major esophageal disorders w mcc",
            "Soft tissue procedures w mcc",
            "Shoulder,elbow or forearm proc,exc major joint proc w cc",
            "Major skin disorders w/o mcc",
            "Malignancy, female reproductive system w cc",
            "Other infectious & parasitic diseases diagnoses w mcc",
            "Other infectious & parasitic diseases diagnoses w/o cc/mcc",
            "Multiple sclerosis & cerebellar ataxia w/o cc/mcc",
            "Epistaxis w/o mcc",
            "Other ear, nose, mouth & throat diagnoses w/o cc/mcc",
            "Dental & oral diseases w cc",
            "Cholecystectomy except by laparoscope w/o c.d.e. w cc",
            "Osteomyelitis w cc",
            "Amputat of lower limb for endocrine,nutrit,& metabol dis w mcc",
            "Simultaneous pancreas/kidney transplant",
            "Spinal procedures w/o cc/mcc",
            "Skin graft for skin ulcer or cellulitis w cc",
            "Cardiac defib implant w cardiac cath w/o ami/hf/shock w mcc",
            "Aicd generator procedures",
            "Cardiac arrest, unexplained w mcc",
            "Hypertensive encephalopathy w cc",
            "Neurological eye disorders",
            "Inflammatory bowel disease w mcc",
            "Inflammatory bowel disease w/o cc/mcc",
            "Foot procedures w cc",
            "Shoulder,elbow or forearm proc,exc major joint proc w mcc",
            "Shoulder,elbow or forearm proc,exc major joint proc w/o cc/mcc",
            "Hand or wrist proc, except major thumb or joint proc w/o cc/mcc",
            "Osteomyelitis w mcc",
            "Signs & symptoms of musculoskeletal system & conn tissue w mcc",
            "Aftercare, musculoskeletal system & connective tissue w mcc",
            "Malignant breast disorders w mcc",
            "Malignant breast disorders w cc",
            "Trauma to the skin, subcut tiss & breast w mcc",
            "Minor skin disorders w mcc",
            "Prostatectomy w cc",
            "Transurethral procedures w/o cc/mcc",
            "Inflammation of the male reproductive system w mcc",
            "Uterine & adnexa proc for ovarian or adnexal malignancy w mcc",
            "Malignancy, female reproductive system w mcc",
            "Menstrual & other female reproductive system disorders w cc/mcc",
            "Reticuloendothelial & immunity disorders w cc",
            "Reticuloendothelial & immunity disorders w/o cc/mcc",
            "Lymphoma & leukemia w major o.r. procedure w mcc",
            "Traumatic injury w/o mcc",
            "Salivary gland procedures",
            "Major bladder procedures w/o cc/mcc",
            "O.r. procedure w principal diagnoses of mental illness",
            "Complications of treatment w/o cc/mcc",
            "Skin ulcers w cc",
            "Periph/cranial nerve & other nerv syst proc w/o cc/mcc",
            "Aftercare, musculoskeletal system & connective tissue w/o cc/mcc",
            "Chemo w acute leukemia as sdx w/o cc/mcc",
            "Extraocular procedures except orbit",
            "Appendectomy w complicated principal diag w/o cc/mcc",
            "Full thickness burn w skin graft or inhal inj w/o cc/mcc",
            "Myeloproliferative disorders or poorly differentiated neoplasms w ot",
            "Radiotherapy",
            "Vagina, cervix & vulva procedures w cc/mcc",
            "Concussion w/o cc/mcc",
            "Multiple sclerosis & cerebellar ataxia w mcc",
            "Vagina, cervix & vulva procedures w/o cc/mcc",
            "Disorders of liver except malig,cirr,alc hepa w/o cc/mcc",
            "Urinary stones w/o esw lithotripsy w mcc",
            "Cholecystectomy except by laparoscope w/o c.d.e. w/o cc/mcc",
            "Rehabilitation w cc/mcc",
            "Malignancy of hepatobiliary system or pancreas w/o cc/mcc",
            "Breast biopsy, local excision & other breast procedures w/o cc/mcc",
            "Kidney & urinary tract neoplasms w cc",
            "Aftercare w/o cc/mcc",
            "Rehabilitation w/o cc/mcc",
            "Benign prostatic hypertrophy w/o mcc",
            "Spinal disorders & injuries w cc/mcc",
            "Spinal disorders & injuries w/o cc/mcc",
            "Other hepatobiliary or pancreas o.r. procedures w mcc",
            "Skin graft exc for skin ulcer or cellulitis w/o cc/mcc",
            "Skin grafts & wound debrid for endoc, nutrit & metab dis w/o cc/mcc",
            "Other myeloprolif dis or poorly diff neopl diag w cc",
            "Orbital procedures w/o cc/mcc",
            "Intraocular procedures w/o cc/mcc",
            "Ear, nose, mouth & throat malignancy w cc",
            "Biliary tract proc except only cholecyst w or w/o c.d.e. w mcc",
            "Vaginal delivery w complicating diagnoses",
            "Mastectomy for malignancy w/o cc/mcc",
            "Mouth procedures w cc/mcc",
            "Major skin disorders w mcc",
            "Hand or wrist proc, except major thumb or joint proc w cc/mcc",
            "Dental & oral diseases w mcc",
            "Anal & stomal procedures w cc",
            "Local excision & removal int fix devices exc hip & femur w cc",
            "Local excision & removal int fix devices exc hip & femur w/o cc/mcc",
            "Reticuloendothelial & immunity disorders w mcc",
            "Myeloprolif disord or poorly diff neopl w maj o.r. proc w/o cc/mcc",
            "Lymphoma & non-acute leukemia w/o cc/mcc",
            "O.r. proc w diagnoses of other contact w health services w/o cc/mcc",
            "Coronary bypass w ptca w mcc",
            "Cardiac pacemaker revision except device replacement w/o cc/mcc",
            "Pelvic evisceration, rad hysterectomy & rad vulvectomy w/o cc/mcc",
            "Wound debridements for injuries w mcc",
            "Cardiac pacemaker device replacement w/o mcc",
            "Non-extensive o.r. proc unrelated to principal diagnosis w/o cc/mcc",
            "Non-bacterial infect of nervous sys exc viral meningitis w mcc",
            "Cardiac defib implant w cardiac cath w ami/hf/shock w mcc",
            "Hepatobiliary diagnostic procedures w mcc",
            "Thyroid, parathyroid & thyroglossal procedures w mcc",
            "Other factors influencing health status",
            "Cranial/facial procedures w/o cc/mcc",
            "Full thickness burn w/o skin grft or inhal inj",
            "O.r. procedures for obesity w mcc",
            "Skin grafts & wound debrid for endoc, nutrit & metab dis w mcc",
            "Non-bacterial infect of nervous sys exc viral meningitis w cc",
            "D&c, conization, laparoscopy & tubal interruption w cc/mcc",
            "Headaches w mcc",
            "Connective tissue disorders w/o cc/mcc",
            "Upper limb & toe amputation for circ system disorders w mcc",
            "Cholecystectomy except by laparoscope w/o c.d.e. w mcc",
            "Hypertensive encephalopathy w mcc",
            "Upper limb & toe amputation for circ system disorders w cc",
            "Kidney & urinary tract neoplasms w mcc",
            "Cesarean section w/o cc/mcc",
            "Pneumothorax w/o cc/mcc",
            "Interstitial lung disease w/o cc/mcc"
            ];
            
            $(function(){
                $("#searchBy").on("change", function(){
                    if($(this).val() == "desc") {
                        $('#desc').suggest(listOfProcedures,{});
                    }
                    else {
                         $('#desc').unbind();
                    }
                });
            });
            
            document.getElementById("searchBy").addEventListener('change', changeSearchBar);
            
            function changeSearchBar() {
               var searchBy = document.getElementById("searchBy").value;
                var searchBar = document.getElementById("desc");
                if(searchBy == "code")
                {
                    searchBar.placeholder = "eg - 023";
                }
                else
                {
                    searchBar.placeholder = "eg - Chest pain";
                } 
                
                searchBar.value = "";
                document.getElementById("error").innerHTML = "";
            }
            

    </script>
  </body>
</html>
